class DARTDesc {
  static Map code = {
    "Depth_First_Search": """""",
    "Breadth_First_Search": """""",
    "Binary_Search": """""",
    "Linear_Search": """""",
    "Bubble_Sort": """""",
    "Heap_Sort": """""",
    "Insertion_Sort": """""",
    "Merge_Sort": """""",
    "Quick_Sort": """""",
    "Selection_Sort": """""",
    "Even_Odd": """""",
    "Factorial": """""",
    "Fibonacci": """""",
    "Greatest_Common_Divisor": """""",
    "Lowest_Common_Multiple": """""",
    "Max_Pairwise_Product": """""",
    "Prime_Numbers": """""",
    "Swap_Numbers": """""",
    "AVL_Tree": """""",
    "Array_Methods": """""",
    "Binary_Search_Tree": """""",
    "Huffman_Tree": """""",
    "Infix_to_Postfix": """""",
    "Infix_to_Prefix": """""",
    "Intersect_Arrays": """""",
    "Postfix_to_Infix": """""",
    "Prefix_to_Infix": """""",
    "Priority_Queue": """""",
    "Queue_using_Array": """""",
    "Queue_using_Linked_List": """""",
    "Queue_using_Stacks": """""",
    "Reverse_Linked_List": """""",
    "Stack_using_Array": """""",
    "Stack_using_Linked_List": """""",
    "Stack_using_Queues": """""",
    "Union_Array": """""",
    "Union_Sorted_Array": """""",
    "Knapsack_Problem": """""",
  };
}
